### ISSUE TITLE
Unable to compile test examples

### ISSUE THREAD

**Issue by oleksii-sl** [jgsogo/wordnet-blast#2]
I want to reuse you wordnet-blast implementation in my project related to boosting existing python code, but I fail to compile test example
There is example in readme which fails if I compile like this:
`g++ -Wall -g -I./ -I./wnb/core -L./lib -lwnb wd-test.cpp`
with undefined references
```
/wordnet-blast/wd-test.cpp:9: undefined reference to `wnb::wordnet::wordnet(std::__cxx11::basic_string<char, std::char_traits<ch
ar>, std::allocator<char> > const&, bool)' 
/wordnet-blast/wd-test.cpp:10: undefined reference to `wnb::wordnet::get_synsets(std::__cxx11::basic_string<char, std::char_trai
ts<char>, std::allocator<char> > const&, wnb::pos_t)' 
/wordnet-blast/wd-test.cpp:11: undefined reference to `wnb::wordnet::get_synsets(std::__cxx11::basic_string<char, std::char_trai
ts<char>, std::allocator<char> > const&, wnb::pos_t)' 
collect2: error: ld returned 1 exit status
```
I found your example in tests folder but make fails too with:
`tests/main.cc:9:31: fatal error: wnb/core/wordnet.hh: No such file or directory`
If I compile it directly using:
`g++ -Wall -g -I../ -I../wnb/core -L../ -lwnb -std=c++11 main.cc`
it fails with same undefined references(

`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)`
These undefined reference errors seem to be dummy (I'm not c++ dev) but they are strange because I pass -lwnb so linker should have all needed
Can you help me with this issue?

**Comment by jgsogo** [comment]
I've added CI jobs for several compilers in Windows and Linux, all of them are working.

The recomended way to build (this fork of) the project is using CMake, I haven't edit the `README` file because I think it _somehow belongs_ to the upstream repository owned by @jardon-u, but maybe I must do it.

To build using CMake just type:

```
git clone https://github.com/jgsogo/wordnet-blast.git
cd wordnet-blast
mkdir build && cd build
cmake .. -DBOOST_ROOT:PATH=<path/to/boost> -DBUILD_TESTS:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=<your/install/dir>
cmake --build . --target install
```
(Last command in linux can be replaced by `make && make install` if the default generator configured for CMake are Makefiles)

Also, you can use CMake verbosity flag to see all flags passed to the compiler (`-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`)

Tell me if you are able to build the project, thanks!

**Comment by oleksii-sl** [comment]
yes, able to build the project
succeed to compile test file by moving -lwnb to the end of compile statement, weird behavior btw
I guess we can close this
